import lume from "lume/mod.ts";
import jsx from "lume/plugins/jsx.ts";
import attributes from "lume/plugins/attributes.ts";
import base_path from "lume/plugins/base_path.ts";
import brotli from "lume/plugins/brotli.ts";
import check_urls from "lume/plugins/check_urls.ts";
import code_highlight from "lume/plugins/code_highlight.ts";
import date from "lume/plugins/date.ts";
import esbuild from "lume/plugins/esbuild.ts";
import eta from "lume/plugins/eta.ts";
import favicon from "lume/plugins/favicon.ts";
import feed from "lume/plugins/feed.ts";
import fff from "lume/plugins/fff.ts";
import filter_pages from "lume/plugins/filter_pages.ts";
import google_fonts from "lume/plugins/google_fonts.ts";
import gzip from "lume/plugins/gzip.ts";
import inline from "lume/plugins/inline.ts";
import json_ld from "lume/plugins/json_ld.ts";
import katex from "lume/plugins/katex.ts";
import lightningcss from "lume/plugins/lightningcss.ts";
import mdx from "lume/plugins/mdx.ts";
import metas from "lume/plugins/metas.ts";
import minify_html from "lume/plugins/minify_html.ts";
import modify_urls from "lume/plugins/modify_urls.ts";
import multilanguage from "lume/plugins/multilanguage.ts";
import nav from "lume/plugins/nav.ts";
import og_images from "lume/plugins/og_images.ts";
import on_demand from "lume/plugins/on_demand.ts";
import pagefind from "lume/plugins/pagefind.ts";
import picture from "lume/plugins/picture.ts";
import plaintext from "lume/plugins/plaintext.ts";
import plugins from "lume/plugins/plugins.ts";
import prism from "lume/plugins/prism.ts";
import pug from "lume/plugins/pug.ts";
import purgecss from "lume/plugins/purgecss.ts";
import reading_info from "lume/plugins/reading_info.ts";
import redirects from "lume/plugins/redirects.ts";
import relations from "lume/plugins/relations.ts";
import relative_urls from "lume/plugins/relative_urls.ts";
import remark from "lume/plugins/remark.ts";
import resolve_urls from "lume/plugins/resolve_urls.ts";
import robots from "lume/plugins/robots.ts";
import sheets from "lume/plugins/sheets.ts";
import slugify_urls from "lume/plugins/slugify_urls.ts";
import svgo from "lume/plugins/svgo.ts";
import tailwindcss from "lume/plugins/tailwindcss.ts";
import postcss from "lume/plugins/postcss.ts";
import terser from "lume/plugins/terser.ts";
import transform_images from "lume/plugins/transform_images.ts";
import toml from "lume/plugins/toml.ts";
import unocss from "lume/plugins/unocss.ts";

const site = lume();

site.use(jsx());
site.use(attributes());
site.use(base_path());
site.use(brotli());
site.use(check_urls());
site.use(code_highlight());
site.use(date());
site.use(esbuild());
site.use(eta());
site.use(favicon());
site.use(feed());
site.use(fff());
site.use(filter_pages());
site.use(google_fonts());
site.use(gzip());
site.use(inline());
site.use(json_ld());
site.use(katex());
site.use(lightningcss());
site.use(mdx());
site.use(metas());
site.use(minify_html());
site.use(modify_urls());
site.use(multilanguage());
site.use(nav());
site.use(og_images());
site.use(on_demand());
site.use(pagefind());
site.use(picture());
site.use(plaintext());
site.use(plugins());
site.use(prism());
site.use(pug());
site.use(purgecss());
site.use(reading_info());
site.use(redirects());
site.use(relations());
site.use(relative_urls());
site.use(remark());
site.use(resolve_urls());
site.use(robots());
site.use(sheets());
site.use(slugify_urls());
site.use(svgo());
site.use(tailwindcss());
site.use(postcss());
site.use(terser());
site.use(transform_images());
site.use(toml());
site.use(unocss());

export default site;
