# Site Configuration
[site]
  title            = "Akordium"
  description      = "Partner digital yang peduli untuk perkembangan bisnis Anda serta mengedepankan kenyamanan dan kolaborasi bersama"
  tagline          = "Your Digital Partner for Growth"
  taglineSeparator = ""
  baseUrl          = "https://akordium.id"
  logo             = "/logo.svg"
  logoWhite        = "/logo.svg"
  logoText         = "Akordium"
  logoWidth        = "30px"
  logoHeight       = "30px"
  trailingSlash = true

  [site.favicon]
    image = "/logo.svg"

# SEO Metadata
[seo]
  author   = "Akordium"
  keywords = ["akordium", "digital", "web development", "app development", "software company"]
  robots   = "index, follow"

  [seo.robotsTxt]
    enable   = true
    disallow = []

  [seo.sitemap]
    enable = true
    exclude = []

# Contact Information
[contact]
  location = "Jl. Pagesangan Agung I/84, Surabaya, Jawa Timur, 60233"
  phone    = "+62 815-9988-995"
  email    = "hello@akordium.id"

# Different theme settings
[settings]
  blogFolder        = "blog"
  servicesFolder    = "services"
  caseStudiesFolder = "case-studies"

  pagination   = 6
  stickyHeader = true

  contactFormAction = "https://api.web3forms.com/submit"
  contactFormProvider = "web3forms"

  footerDescription = ""

  [settings.copyright]
    enable = true
    text   = "Copyright © 2024 Akordium. All Rights Reserved."

  [settings.subscription]
    enable     = false
    title      = ""
    formAction = ""

  [settings.multilingual]
    enable               = true
    defaultLanguage      = "en"
    disableLanguages     = []
    showDefaultLangInUrl = false

  [settings.navigationButton]
    enable = true
    label  = ""
    url    = "/contact"

  [settings.announcementBar]
    enable = false
    label  = ""

  [settings.markup.tableOfContents]
    enable     = true
    expanded   = true
    endLevel   = 5
    ordered    = false
    startLevel = 1

# OpenGraph Metadata
[opengraph]
  image       = "/og-image.jpg"
  ogLocale    = "en_US"
  ogType      = "website"
  twitter     = ""
  twitterCard = "summary_large_image"

[head]
  content = ""
